/** Canonical route names. Keep dependency-free: shared by server, client and guards. */
export const ROUTE_NAME: Record<string, string> = {
  "/staff": "Dashboard",
  "/staff/visits/queue": "Reception Queue",
  "/staff/patients": "Patients",
  "/staff/appointments": "Appointments",
  "/staff/messages": "Website Messages",
  "/staff/visits": "Visit Records",
  "/staff/quote": "Quick Quote",
  "/staff/payments/cash-drawer": "Cash In & Out",
  "/staff/queue": "Queue",
  "/staff/critical-alerts": "Critical Alerts",
  "/staff/results": "Results",
  "/staff/admin/accounting/hmo-claims": "HMO Claims",
  "/staff/admin/accounting/ap": "Expenses Overview",
  "/staff/admin/accounting/pf-payouts": "Pay Doctors",
  "/staff/admin/accounting/pf-ytd-summary": "Doctor Pay (This Year)",
  "/staff/admin/accounting/send-out-labs": "Send-out Labs",
  "/staff/admin/payroll/runs": "Run Payroll",
  "/staff/admin/payroll/periods": "Pay Periods",
  "/staff/admin/payroll/employees": "Employees",
  "/staff/admin/payroll/ot-slips": "Overtime Slips",
  "/staff/admin/payroll/leaves": "Leaves",
  "/staff/admin/payroll/holidays": "Holidays",
  "/staff/admin/payroll/rates": "Government Rates (SSS, PhilHealth, Pag-IBIG, Tax)",
  "/staff/admin/payroll/settings": "Payroll Settings",
  "/staff/admin/reports/staff-advances": "Staff Cash Advances",
  "/staff/admin/accounting/journal": "Journal Entries",
  "/staff/admin/accounting/financial-statements": "Income Statement",
  "/staff/admin/accounting/variance": "Budget vs Actual",
  "/staff/admin/accounting/bank-rec": "Bank Reconciliation",
  "/staff/admin/accounting/periods": "Monthly Periods",
  "/staff/admin/accounting/accrual-templates": "Recurring Monthly Entries",
  "/staff/admin/operations/daily-revenue": "Daily Revenue",
  "/staff/admin/operations": "Daily Sheet",
  "/staff/admin/reports/lab-tat": "Lab Turnaround Time",
  "/staff/admin/reports/stuck-tests": "Stuck Tests",
  "/staff/admin/reports/undone-releases": "Undone Releases",
  "/staff/admin/reports/deleted-entries": "Deleted Queue Entries",
  "/staff/admin/reports/payment-changes": "Payment Changes",
  "/staff/admin/reports/patients-without-consent": "Patients Without Consent",
  "/staff/admin/accounting": "External Sync Status",
  "/staff/admin/closures": "Closures",
  "/staff/admin/inventory": "Inventory",
  "/staff/admin/gift-codes": "Gift Codes",
  "/staff/admin/newsletter": "Newsletter",
  "/staff/marketing": "Ad Performance",
  "/staff/admin/prices": "Prices",
  "/staff/services": "Services",
  "/staff/admin/discounts": "Discounts",
  "/staff/admin/result-templates": "Result Templates",
  "/staff/admin/hmo-providers": "HMO Providers",
  "/staff/admin/physicians": "Physicians",
  "/staff/admin/accounting/chart-of-accounts": "Chart of Accounts",
  "/staff/admin/accounting/money-routing": "Money Routing",
  "/staff/users": "Staff Users",
  "/staff/audit": "Audit Log",
  "/staff/admin/emails-sent": "Emails Sent",
  "/staff/admin/settings/dashboard-cards": "Dashboard Settings",
  "/staff/admin/seo": "Search Engines (IndexNow)",
  "/staff/admin/settings/consent-gate": "Consent Gate",
  "/staff/admin/settings/online-booking": "Online Booking",
  "/staff/admin/settings/alerts": "Email Alerts",
  "/staff/admin/import-patients": "Import Patients",
  "/staff/admin/patient-merge": "Merge Duplicate Patients",
  "/staff/admin/deleted-patients": "Deleted Patients",
  "/staff/profile": "My Profile",
  "/staff/payslips": "My Payslips",
  "/staff/gift-codes/sell": "Sell Gift Code",
  "/staff/gift-codes/refund": "Refund Gift Code Sale",
  "/staff/registration": "Registration Link",
  "/staff/signoff": "Sign-off",
  "/staff/admin/accounting/patient-ar": "Patient Receivables (Aging)",
  "/staff/marketing/ops": "Ops Tracker",
  "/staff/marketing/sources": "Booking Sources",
  "/staff/payments/petty-cash": "Petty Cash",
  "/staff/payments/eod": "End of Day",
  "/staff/visits/new": "New Visit",
  "/staff/admin/operations/cash": "Cash & Cards",
  "/staff/admin/operations/expenses": "Expenses & P&L",
  "/staff/admin/operations/hmo": "HMO Receivables",
  "/staff/admin/operations/trends": "Monthly Trends",
  "/staff/admin/accounting/ap/bills": "Vendor Bills",
  "/staff/admin/accounting/ap/payments": "Bill Payments",
  "/staff/admin/accounting/ap/vendors": "Vendors",
  "/staff/admin/accounting/ap/recurring": "Recurring Bills",
  "/staff/admin/accounting/financial-statements/balance-sheet": "Balance Sheet",
  "/staff/admin/accounting/financial-statements/cash-flow": "Cash Flow",
  "/staff/patients/new": "New Patient",
  "/staff/admin/accounting/ap/quick-expense": "Quick Expense",
  "/staff/admin/operations/cron-health": "Cron Health",
  // Record pages retain their static name when the authorized lookup is absent.
  "/staff/admin/accounting/bank-rec/[id]": "Bank statement",
  "/staff/admin/accounting/hmo-claims/[providerId]": "HMO provider",
  "/staff/admin/accounting/hmo-claims/[providerId]/historic/[claimId]": "Historic HMO claim",
  "/staff/admin/accounting/hmo-claims/batches/[batchId]": "HMO claim batch",
  "/staff/admin/accounting/pf-payouts/[id]": "PF Disbursement",
  "/staff/admin/accounting/pf-payouts/[id]/slip": "PF payout slip",
  "/staff/admin/gift-codes/[id]": "Gift code",
  "/staff/admin/hmo-providers/[id]/edit": "Edit HMO provider",
  "/staff/admin/inventory/[id]": "Inventory item",
  "/staff/admin/inventory/[id]/edit": "Edit inventory item",
  "/staff/admin/payroll/employees/[id]": "Employee",
  "/staff/admin/payroll/runs/[id]": "Pay run",
  "/staff/admin/payroll/runs/[id]/dtr": "Import DTR",
  "/staff/patients/[id]": "Patient",
  "/staff/patients/[id]/consent/print": "Consent form",
  "/staff/patients/[id]/consent/signed": "Signed consent form",
  "/staff/patients/[id]/edit": "Edit patient",
  "/staff/payslips/[id]": "Payslip",
  "/staff/queue/[id]": "Test",
  "/staff/queue/consolidated/[visitId]/[groupId]": "Chemistry report",
  "/staff/visits/[id]": "Visit",
  "/staff/visits/[id]/receipt": "Receipt",
  "/staff/visits/[id]/statement": "Statement",
  "/staff/visits/group/[groupId]/receipt": "Combined receipt"
};

/** Umbrella links name the section, even when its landing page is a specific view. */
export const SECTION_NAME: Record<string, string> = {
  "/staff/payments/cash-drawer": "Cash Drawer",
  "/staff/admin/accounting/ap": "Expenses",
  "/staff/admin/operations": "Daily Monitoring",
  "/staff/admin/accounting/financial-statements": "Financial Statements",
  "/staff/marketing": "Marketing"
};
