import { notFound } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireAdminStaff } from "@/lib/auth/require-admin";
import {
  DtrUploadClient,
  type DtrImportRow,
  type DtrRowFlagged,
  type EmployeeOption,
  type RunHeader,
  type StatusCounts,
} from "./dtr-upload-client";

export const metadata = { title: "Import DTR — payroll admin" };
export const dynamic = "force-dynamic";

interface PageProps {
  params: Promise<{ id: string }>;
}

export default async function DtrUploadPage({ params }: PageProps) {
  await requireAdminStaff();
  const { id: runId } = await params;

  const admin = createAdminClient();

  // -- 1. The run + its period. Used for the breadcrumb header. If the run
  // doesn't exist, 404 — we never want to render an "Import DTR" UI for a
  // ghost run.
  const { data: runRow, error: runErr } = await admin
    .from("payroll_runs")
    .select(
      `id, status, period_id,
       period:payroll_periods!inner(id, period_start, period_end, pay_date)`,
    )
    .eq("id", runId)
    .maybeSingle();
  if (runErr) {
    console.error("[payroll/runs/[id]/dtr] run fetch failed:", runErr);
    notFound();
  }
  if (!runRow) {
    notFound();
  }
  const periodJoin = Array.isArray(runRow.period)
    ? runRow.period[0]
    : runRow.period;
  if (!periodJoin) {
    notFound();
  }
  const periodId = periodJoin.id;

  // -- 2. Prior imports for this period (most recent first). Embed the
  // uploader's staff_profile so we can show "By <name>". The FK relation name
  // is generated by Supabase: payroll_dtr_imports_uploaded_by_fkey.
  type RawImportRow = {
    id: string;
    filename: string | null;
    parsed_rows_count: number;
    uploaded_at: string;
    uploaded_by: string;
    uploader:
      | { full_name: string | null }
      | { full_name: string | null }[]
      | null;
  };
  const { data: rawImports, error: importsErr } = await admin
    .from("payroll_dtr_imports")
    .select(
      `id, filename, parsed_rows_count, uploaded_at, uploaded_by,
       uploader:staff_profiles!payroll_dtr_imports_uploaded_by_fkey(full_name)`,
    )
    .eq("period_id", periodId)
    .order("uploaded_at", { ascending: false })
    .returns<RawImportRow[]>();
  if (importsErr) {
    console.error("[payroll/runs/[id]/dtr] imports fetch failed:", importsErr);
  }
  const imports = rawImports ?? [];

  // The "current" import is the most-recent one. Any earlier import has had
  // its rows flipped to status='superseded' by uploadDtrAction.
  const currentImport = imports[0] ?? null;

  // -- 3. Status-count summary for the current import's rows. We aggregate
  // client-side because PostgREST has no native GROUP BY without RPC.
  const counts: StatusCounts = {
    parsed: 0,
    flagged_no_employee: 0,
    flagged_missing_punch: 0,
    superseded: 0,
    other: 0,
    total: 0,
  };

  let flaggedNoEmployeeRows: DtrRowFlagged[] = [];
  if (currentImport) {
    const { data: rows, error: rowsErr } = await admin
      .from("payroll_dtr_rows")
      .select(
        "id, status, external_id_raw, work_date, time_in, time_out, total_hours",
      )
      .eq("import_id", currentImport.id);
    if (rowsErr) {
      console.error(
        "[payroll/runs/[id]/dtr] rows fetch failed:",
        rowsErr,
      );
    }
    for (const r of rows ?? []) {
      counts.total += 1;
      if (r.status === "parsed") counts.parsed += 1;
      else if (r.status === "flagged_no_employee") counts.flagged_no_employee += 1;
      else if (r.status === "flagged_missing_punch")
        counts.flagged_missing_punch += 1;
      else if (r.status === "superseded") counts.superseded += 1;
      else counts.other += 1;
    }
    flaggedNoEmployeeRows = (rows ?? [])
      .filter((r) => r.status === "flagged_no_employee")
      .map((r) => ({
        id: r.id,
        external_id_raw: r.external_id_raw,
        work_date: r.work_date,
        time_in: r.time_in,
        time_out: r.time_out,
        total_hours: r.total_hours === null ? null : Number(r.total_hours),
      }));
  }

  // -- 4. Active employees for the reconcile dropdown.
  type RawEmployee = {
    id: string;
    employee_number: string | null;
    staff_profile:
      | { full_name: string | null }
      | { full_name: string | null }[]
      | null;
  };
  const { data: empRows, error: empErr } = await admin
    .from("employees")
    .select(
      "id, employee_number, staff_profile:staff_profiles!inner(full_name)",
    )
    .eq("is_active", true)
    .returns<RawEmployee[]>();
  if (empErr) {
    console.error("[payroll/runs/[id]/dtr] employees fetch failed:", empErr);
  }
  const employees: EmployeeOption[] = (empRows ?? [])
    .map((e) => {
      const profile = Array.isArray(e.staff_profile)
        ? e.staff_profile[0]
        : e.staff_profile;
      return {
        id: e.id,
        full_name: profile?.full_name ?? "(unknown)",
        employee_number: e.employee_number,
      };
    })
    .sort((a, b) => a.full_name.localeCompare(b.full_name));

  // -- 5. Shape imports for the client. "Current" is the most-recent row.
  const importList: DtrImportRow[] = imports.map((row, idx) => {
    const uploader = Array.isArray(row.uploader)
      ? row.uploader[0]
      : row.uploader;
    return {
      id: row.id,
      filename: row.filename,
      parsed_rows_count: row.parsed_rows_count,
      uploaded_at: row.uploaded_at,
      uploader_name: uploader?.full_name ?? "(unknown)",
      is_current: idx === 0,
    };
  });

  const runHeader: RunHeader = {
    id: runRow.id,
    period_id: periodId,
    period_start: periodJoin.period_start,
    period_end: periodJoin.period_end,
    pay_date: periodJoin.pay_date,
  };

  return (
    <DtrUploadClient
      run={runHeader}
      imports={importList}
      currentImportId={currentImport?.id ?? null}
      counts={counts}
      flaggedRows={flaggedNoEmployeeRows}
      employees={employees}
    />
  );
}
