// Regenerated by `npm run db:types`. Stub until Phase 1 migrations exist.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = Record<string, never>;
