-- =============================================================================
-- 0043_eod_cash_reconciliation.sql
-- =============================================================================
-- Phase 12.C: Daily cash reconciliation. Adds reception-facing end-of-day
-- close workflow, cash adjustments subledger, staff-advance receivable
-- subledger, and the GL bridge that turns each cash movement into a
-- balanced JE through the same pattern as 0030 (draft → lines → posted).
--
-- After this migration:
--   * /staff/payments/cash-drawer logs petty cash, salary advances, courier
--     payouts, and float adjustments. Each fires a balanced JE in-transaction.
--   * /staff/payments/eod closes the day; non-zero variance posts a cash
--     short/over JE.
--   * Closed (date, shift) combos are DB-locked (P0015) until admin reopens.
--   * salary_advance payouts mirror into staff_advances; 12.6 (payroll) will
--     draw down outstanding balances via payslip deductions.
--   * /staff/admin/accounting/cash-routing manages the kind → CoA map.
--   * /staff/admin/reports/{daily-revenue,staff-advances} are read-only views.
--
-- NOTE: Existing partial unique index from 0030
--   journal_entries_one_posted_per_source
-- already covers the two new source_kind values; no index change needed.
-- =============================================================================

-- ---- Enum additions --------------------------------------------------------
-- Must run before any function/trigger that references these values.
-- IMPORTANT: ALTER TYPE … ADD VALUE inside a transaction does NOT make the
-- new enum value visible to later statements in that same transaction in
-- PG <12. Supabase runs PG 15+, where the value IS visible — verified by
-- 12.3's migration 0034 (which used the same pattern). If you back-port
-- this to a PG <12 environment, split into two migrations.
alter type public.je_source_kind add value if not exists 'cash_adjustment';
alter type public.je_source_kind add value if not exists 'eod_close';
