-- =============================================================================
-- 0045 — Private storage bucket `payslips` for payroll PDFs
-- =============================================================================
-- Phase 12.6 (Payroll) — D4: a private bucket that stores per-cycle payslip
-- PDFs generated by the admin "Generate payslips" action.
--
-- Path convention: <employee_id>/<period_start>_<period_end>.pdf
--   e.g. 'd9b9.../2026-05-01_2026-05-15.pdf'
--
-- Access model:
--   - Admins (staff with role='admin') read/write everything via the
--     service-role client or via authenticated session.
--   - Employees read only files whose first path segment matches the
--     `employees.id` linked to their `staff_profile_id` (= auth.uid()).
--   - Patients have no Supabase Auth account and therefore cannot reach
--     this bucket at all (no anon policy is created).
--
-- file_size_limit / allowed_mime_types are added (matching 0017, 0038's
-- precedent) to defensively cap payload size and reject non-PDF uploads.
-- A 2-page payslip PDF is ~50-200 KB; 10 MB is generous headroom.
-- =============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'payslips',
  'payslips',
  false,
  10485760,                       -- 10 MB
  array['application/pdf']
)
on conflict (id) do nothing;


-- ---------------------------------------------------------------------------
-- RLS policies on storage.objects
-- ---------------------------------------------------------------------------
-- Bucket-level RLS: admin can read/write everything; employees can read only
-- files in their own folder. The folder is the employee_id (UUID).
create policy "payslips: admin all"
  on storage.objects for all to authenticated
  using (bucket_id = 'payslips' and public.has_role(array['admin']))
  with check (bucket_id = 'payslips' and public.has_role(array['admin']));

create policy "payslips: self read"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'payslips'
    and (storage.foldername(name))[1] in (
      select id::text from public.employees where staff_profile_id = auth.uid()
    )
  );
