-- =============================================================================
-- 0055_referral_sources_lookup.sql
-- =============================================================================
-- Replaces the hardcoded CHECK constraint on patients.referral_source
-- (added in 0011) with a lookup table. New categories (e.g. Instagram,
-- TikTok, Returning patient, Gift code) can now be added via INSERT
-- without a code migration. The 12 seed values include the original 8
-- from 0011 plus 4 the legacy importer needs to map to.
-- =============================================================================

create table public.referral_sources (
  id          text primary key,
  label       text not null,
  sort_order  int  not null default 100,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- Seed values. ids match the 0011 enum values so existing patients.referral_source
-- entries continue to validate against the new FK.
insert into public.referral_sources (id, label, sort_order) values
  ('doctor_referral',             'Doctor referral',                   10),
  ('customer_referral',           'Customer referral',                 20),
  ('online_facebook',             'Facebook',                          30),
  ('online_website',              'Website',                           40),
  ('online_google',               'Google',                            50),
  ('online_instagram',            'Instagram',                         60),
  ('online_tiktok',               'TikTok',                            70),
  ('walk_in',                     'Walk-in',                           80),
  ('returning_patient',           'Returning patient',                 90),
  ('tenant_employee_northridge',  'Northridge tenant / employee',     100),
  ('gift_code',                   'Gift code',                        110),
  ('other',                       'Other',                            120);

-- Drop the old CHECK constraint and add an FK pointing at the lookup.
-- (Constraint name is auto-generated by Postgres for inline CHECKs; the
-- IF EXISTS makes this safe regardless of the actual suffix.)
alter table public.patients
  drop constraint if exists patients_referral_source_check;

alter table public.patients
  add constraint patients_referral_source_fk
  foreign key (referral_source) references public.referral_sources(id)
  on delete restrict;

-- RLS: read-by-anyone (it's a public dropdown source); writes are
-- service-role only until an admin UI ships.
alter table public.referral_sources enable row level security;

create policy "referral_sources: public read"
  on public.referral_sources for select to anon, authenticated
  using (true);
