-- 0151: evaluate RLS helper functions once per query, not once per row.
--
-- has_role(), is_staff(), staff_role() and current_patient_id() are all STABLE, but
-- STABLE does not tell the planner to call them once — it only promises the answer
-- will not change within the statement. Written bare in a policy USING clause the
-- call is a per-row filter, so a staff user reading the 25,604-row test_requests
-- table did roughly 75,000-100,000 staff_profiles index lookups for ONE page load.
-- That is the whole reason visits_classification_summary took 2,733 ms (max 7,571 ms)
-- against a 12 MB table, and the Visits list 1,850 ms.
--
-- Wrapping each call as (select fn(...)) turns it into an InitPlan: computed once.
--
-- Supabase's own advisor does NOT catch this. Its auth_rls_initplan lint sees only
-- direct auth.*() calls, not a helper like has_role() that wraps auth.uid() one level
-- down — it reported 10 when the real number was 149 of 160 policies.
--
-- Phase 1 below is GENERATED by scripts/perf/generate-rls-initplan-migration.ts and
-- committed as static DDL. It is semantically inert BY CONSTRUCTION, and that is
-- proved rather than asserted: scripts/perf/rls-structural-prove.ts unwraps every
-- post-migration expression and compares it byte-for-byte with the pre-migration
-- one, across ALL tables — populated or empty. Row-visibility sampling
-- (scripts/perf/rls-equivalence-prove.ts) gates Phase 2, where meaning does change.
--
-- No new P-code: this migration raises no exceptions.
-- Function ACLs untouched: no helper is redefined, and grants survive a policy
-- replace (reloptions do not, but no view is redefined here either).

-- ---------------------------------------------------------------------------
-- Phase 1 — InitPlan hoisting (generated; semantically inert)
-- ---------------------------------------------------------------------------

-- accounting_periods: accounting_periods: admin read
drop policy "accounting_periods: admin read" on public."accounting_periods";
create policy "accounting_periods: admin read" on public."accounting_periods"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- accounting_settings: accounting_settings: admin all
drop policy "accounting_settings: admin all" on public."accounting_settings";
create policy "accounting_settings: admin all" on public."accounting_settings"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- accounting_settings: accounting_settings: staff read
drop policy "accounting_settings: staff read" on public."accounting_settings";
create policy "accounting_settings: staff read" on public."accounting_settings"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- accrual_template_lines: accrual_template_lines: admin read
drop policy "accrual_template_lines: admin read" on public."accrual_template_lines";
create policy "accrual_template_lines: admin read" on public."accrual_template_lines"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- accrual_template_lines: accrual_template_lines: admin write
drop policy "accrual_template_lines: admin write" on public."accrual_template_lines";
create policy "accrual_template_lines: admin write" on public."accrual_template_lines"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- accrual_templates: accrual_templates: admin read
drop policy "accrual_templates: admin read" on public."accrual_templates";
create policy "accrual_templates: admin read" on public."accrual_templates"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- accrual_templates: accrual_templates: admin write
drop policy "accrual_templates: admin write" on public."accrual_templates";
create policy "accrual_templates: admin write" on public."accrual_templates"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- appointment_attachments: appointment_attachments: patient self
drop policy "appointment_attachments: patient self" on public."appointment_attachments";
create policy "appointment_attachments: patient self" on public."appointment_attachments"
  as permissive
  for select
  to anon, authenticated
  using ((patient_id = (select current_patient_id())));

-- appointment_attachments: appointment_attachments: staff read
drop policy "appointment_attachments: staff read" on public."appointment_attachments";
create policy "appointment_attachments: staff read" on public."appointment_attachments"
  as permissive
  for select
  to authenticated
  using ((select is_staff()));

-- appointments: appointments: patient self
drop policy "appointments: patient self" on public."appointments";
create policy "appointments: patient self" on public."appointments"
  as permissive
  for select
  to anon, authenticated
  using ((patient_id = (select current_patient_id())));

-- appointments: appointments: staff manage
drop policy "appointments: staff manage" on public."appointments";
create policy "appointments: staff manage" on public."appointments"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'admin'::text])))
  with check ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- audit_log: audit_log: admin select
drop policy "audit_log: admin select" on public."audit_log";
create policy "audit_log: admin select" on public."audit_log"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- bank_statement_lines: bank_statement_lines: admin read
drop policy "bank_statement_lines: admin read" on public."bank_statement_lines";
create policy "bank_statement_lines: admin read" on public."bank_statement_lines"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- bank_statement_lines: bank_statement_lines: admin write
drop policy "bank_statement_lines: admin write" on public."bank_statement_lines";
create policy "bank_statement_lines: admin write" on public."bank_statement_lines"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- bank_statements: bank_statements: admin read
drop policy "bank_statements: admin read" on public."bank_statements";
create policy "bank_statements: admin read" on public."bank_statements"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- bank_statements: bank_statements: admin write
drop policy "bank_statements: admin write" on public."bank_statements";
create policy "bank_statements: admin write" on public."bank_statements"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- bill_attachments: bill_attachments_admin_all
drop policy "bill_attachments_admin_all" on public."bill_attachments";
create policy "bill_attachments_admin_all" on public."bill_attachments"
  as permissive
  for all
  to public
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- bill_lines: bill_lines_admin_all
drop policy "bill_lines_admin_all" on public."bill_lines";
create policy "bill_lines_admin_all" on public."bill_lines"
  as permissive
  for all
  to public
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- bill_payment_allocations: bill_payment_allocations_admin_all
drop policy "bill_payment_allocations_admin_all" on public."bill_payment_allocations";
create policy "bill_payment_allocations_admin_all" on public."bill_payment_allocations"
  as permissive
  for all
  to public
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- bill_payments: bill_payments_admin_all
drop policy "bill_payments_admin_all" on public."bill_payments";
create policy "bill_payments_admin_all" on public."bill_payments"
  as permissive
  for all
  to public
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- bills: bills_admin_all
drop policy "bills_admin_all" on public."bills";
create policy "bills_admin_all" on public."bills"
  as permissive
  for all
  to public
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- budgets: budgets: admin read
drop policy "budgets: admin read" on public."budgets";
create policy "budgets: admin read" on public."budgets"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- budgets: budgets: admin write
drop policy "budgets: admin write" on public."budgets";
create policy "budgets: admin write" on public."budgets"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- cash_adjustment_account_map: cash_adjustment_account_map: admin read
drop policy "cash_adjustment_account_map: admin read" on public."cash_adjustment_account_map";
create policy "cash_adjustment_account_map: admin read" on public."cash_adjustment_account_map"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- cash_adjustment_account_map: cash_adjustment_account_map: admin write
drop policy "cash_adjustment_account_map: admin write" on public."cash_adjustment_account_map";
create policy "cash_adjustment_account_map: admin write" on public."cash_adjustment_account_map"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- cash_shifts: cash_shifts: admin write
drop policy "cash_shifts: admin write" on public."cash_shifts";
create policy "cash_shifts: admin write" on public."cash_shifts"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- cash_shifts: cash_shifts: staff read
drop policy "cash_shifts: staff read" on public."cash_shifts";
create policy "cash_shifts: staff read" on public."cash_shifts"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- chart_of_accounts: chart_of_accounts: admin read
drop policy "chart_of_accounts: admin read" on public."chart_of_accounts";
create policy "chart_of_accounts: admin read" on public."chart_of_accounts"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- clinic_closures: clinic_closures: admin manage
drop policy "clinic_closures: admin manage" on public."clinic_closures";
create policy "clinic_closures: admin manage" on public."clinic_closures"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- cogs_send_out_entries: cogs_send_out_entries: admin read
drop policy "cogs_send_out_entries: admin read" on public."cogs_send_out_entries";
create policy "cogs_send_out_entries: admin read" on public."cogs_send_out_entries"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- cogs_send_out_trueups: cogs_send_out_trueups: admin read
drop policy "cogs_send_out_trueups: admin read" on public."cogs_send_out_trueups";
create policy "cogs_send_out_trueups: admin read" on public."cogs_send_out_trueups"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- consent_settings: consent_settings: admin manage
drop policy "consent_settings: admin manage" on public."consent_settings";
create policy "consent_settings: admin manage" on public."consent_settings"
  as permissive
  for all
  to public
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- contact_messages: contact_messages: reception/admin manage
drop policy "contact_messages: reception/admin manage" on public."contact_messages";
create policy "contact_messages: reception/admin manage" on public."contact_messages"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'admin'::text])))
  with check ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- critical_alerts: critical_alerts: lab worker insert
drop policy "critical_alerts: lab worker insert" on public."critical_alerts";
create policy "critical_alerts: lab worker insert" on public."critical_alerts"
  as permissive
  for insert
  to authenticated
  with check ((select has_role(ARRAY['medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- critical_alerts: critical_alerts: pathologist/admin acknowledge
drop policy "critical_alerts: pathologist/admin acknowledge" on public."critical_alerts";
create policy "critical_alerts: pathologist/admin acknowledge" on public."critical_alerts"
  as permissive
  for update
  to authenticated
  using ((select has_role(ARRAY['pathologist'::text, 'admin'::text])))
  with check ((select has_role(ARRAY['pathologist'::text, 'admin'::text])));

-- critical_alerts: critical_alerts: staff read
drop policy "critical_alerts: staff read" on public."critical_alerts";
create policy "critical_alerts: staff read" on public."critical_alerts"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- dashboard_card_prefs: dashboard_card_prefs: admin write
drop policy "dashboard_card_prefs: admin write" on public."dashboard_card_prefs";
create policy "dashboard_card_prefs: admin write" on public."dashboard_card_prefs"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- dashboard_card_prefs: dashboard_card_prefs: staff read
drop policy "dashboard_card_prefs: staff read" on public."dashboard_card_prefs";
create policy "dashboard_card_prefs: staff read" on public."dashboard_card_prefs"
  as permissive
  for select
  to authenticated
  using ((select is_staff()));

-- discount_types: discount_types: admin delete
drop policy "discount_types: admin delete" on public."discount_types";
create policy "discount_types: admin delete" on public."discount_types"
  as permissive
  for delete
  to public
  using ((select has_role(ARRAY['admin'::text])));

-- discount_types: discount_types: admin insert
drop policy "discount_types: admin insert" on public."discount_types";
create policy "discount_types: admin insert" on public."discount_types"
  as permissive
  for insert
  to public
  with check ((select has_role(ARRAY['admin'::text])));

-- discount_types: discount_types: admin update
drop policy "discount_types: admin update" on public."discount_types";
create policy "discount_types: admin update" on public."discount_types"
  as permissive
  for update
  to public
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- discount_types: discount_types: staff read
drop policy "discount_types: staff read" on public."discount_types";
create policy "discount_types: staff read" on public."discount_types"
  as permissive
  for select
  to public
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- doctor_pf_disbursements: doctor_pf_disbursements: admin read
drop policy "doctor_pf_disbursements: admin read" on public."doctor_pf_disbursements";
create policy "doctor_pf_disbursements: admin read" on public."doctor_pf_disbursements"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- doctor_pf_entries: doctor_pf_entries: admin read
drop policy "doctor_pf_entries: admin read" on public."doctor_pf_entries";
create policy "doctor_pf_entries: admin read" on public."doctor_pf_entries"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- employee_allowances: employee_allowances: admin all
drop policy "employee_allowances: admin all" on public."employee_allowances";
create policy "employee_allowances: admin all" on public."employee_allowances"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- employee_leave_records: employee_leave_records: admin all
drop policy "employee_leave_records: admin all" on public."employee_leave_records";
create policy "employee_leave_records: admin all" on public."employee_leave_records"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- employee_leave_records: employee_leave_records: self read
drop policy "employee_leave_records: self read" on public."employee_leave_records";
create policy "employee_leave_records: self read" on public."employee_leave_records"
  as permissive
  for select
  to authenticated
  using ((employee_id IN ( SELECT employees.id
   FROM employees
  WHERE (employees.staff_profile_id = (select auth.uid())))));

-- employee_loans: employee_loans: admin all
drop policy "employee_loans: admin all" on public."employee_loans";
create policy "employee_loans: admin all" on public."employee_loans"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- employees: employees: admin all
drop policy "employees: admin all" on public."employees";
create policy "employees: admin all" on public."employees"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- employees: employees: self read
drop policy "employees: self read" on public."employees";
create policy "employees: self read" on public."employees"
  as permissive
  for select
  to authenticated
  using ((staff_profile_id = (select auth.uid())));

-- eod_cash_adjustments: eod_cash_adjustments: staff read
drop policy "eod_cash_adjustments: staff read" on public."eod_cash_adjustments";
create policy "eod_cash_adjustments: staff read" on public."eod_cash_adjustments"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- eod_cash_adjustments: eod_cash_adjustments: staff write
drop policy "eod_cash_adjustments: staff write" on public."eod_cash_adjustments";
create policy "eod_cash_adjustments: staff write" on public."eod_cash_adjustments"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'admin'::text])))
  with check ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- eod_close_records: eod_close_records: admin update
drop policy "eod_close_records: admin update" on public."eod_close_records";
create policy "eod_close_records: admin update" on public."eod_close_records"
  as permissive
  for update
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- eod_close_records: eod_close_records: staff insert
drop policy "eod_close_records: staff insert" on public."eod_close_records";
create policy "eod_close_records: staff insert" on public."eod_close_records"
  as permissive
  for insert
  to authenticated
  with check ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- eod_close_records: eod_close_records: staff read
drop policy "eod_close_records: staff read" on public."eod_close_records";
create policy "eod_close_records: staff read" on public."eod_close_records"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- gift_codes: gift_codes: admin write
drop policy "gift_codes: admin write" on public."gift_codes";
create policy "gift_codes: admin write" on public."gift_codes"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- gift_codes: gift_codes: reception update
drop policy "gift_codes: reception update" on public."gift_codes";
create policy "gift_codes: reception update" on public."gift_codes"
  as permissive
  for update
  to authenticated
  using ((select has_role(ARRAY['reception'::text])))
  with check ((select has_role(ARRAY['reception'::text])));

-- gift_codes: gift_codes: staff read
drop policy "gift_codes: staff read" on public."gift_codes";
create policy "gift_codes: staff read" on public."gift_codes"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- historic_hmo_claims: historic_hmo_claims: admin read
drop policy "historic_hmo_claims: admin read" on public."historic_hmo_claims";
create policy "historic_hmo_claims: admin read" on public."historic_hmo_claims"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- hmo_aging_snapshots: hmo_aging_snapshots: admin read
drop policy "hmo_aging_snapshots: admin read" on public."hmo_aging_snapshots";
create policy "hmo_aging_snapshots: admin read" on public."hmo_aging_snapshots"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- hmo_claim_batches: hmo_claim_batches: admin read
drop policy "hmo_claim_batches: admin read" on public."hmo_claim_batches";
create policy "hmo_claim_batches: admin read" on public."hmo_claim_batches"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- hmo_claim_items: hmo_claim_items: admin read
drop policy "hmo_claim_items: admin read" on public."hmo_claim_items";
create policy "hmo_claim_items: admin read" on public."hmo_claim_items"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- hmo_claim_resolutions: hmo_claim_resolutions: admin read
drop policy "hmo_claim_resolutions: admin read" on public."hmo_claim_resolutions";
create policy "hmo_claim_resolutions: admin read" on public."hmo_claim_resolutions"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- hmo_payment_allocations: hmo_payment_allocations: admin read
drop policy "hmo_payment_allocations: admin read" on public."hmo_payment_allocations";
create policy "hmo_payment_allocations: admin read" on public."hmo_payment_allocations"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- hmo_providers: hmo_providers: admin manage
drop policy "hmo_providers: admin manage" on public."hmo_providers";
create policy "hmo_providers: admin manage" on public."hmo_providers"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- hmo_providers: hmo_providers: staff read all
drop policy "hmo_providers: staff read all" on public."hmo_providers";
create policy "hmo_providers: staff read all" on public."hmo_providers"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- inquiries: inquiries: admin delete
drop policy "inquiries: admin delete" on public."inquiries";
create policy "inquiries: admin delete" on public."inquiries"
  as permissive
  for delete
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- inquiries: inquiries: reception update
drop policy "inquiries: reception update" on public."inquiries";
create policy "inquiries: reception update" on public."inquiries"
  as permissive
  for update
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'admin'::text])))
  with check ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- inquiries: inquiries: reception write
drop policy "inquiries: reception write" on public."inquiries";
create policy "inquiries: reception write" on public."inquiries"
  as permissive
  for insert
  to authenticated
  with check ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- inquiries: inquiries: staff read
drop policy "inquiries: staff read" on public."inquiries";
create policy "inquiries: staff read" on public."inquiries"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- inventory_items: inventory_items: admin write
drop policy "inventory_items: admin write" on public."inventory_items";
create policy "inventory_items: admin write" on public."inventory_items"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- inventory_items: inventory_items: staff read
drop policy "inventory_items: staff read" on public."inventory_items";
create policy "inventory_items: staff read" on public."inventory_items"
  as permissive
  for select
  to authenticated
  using ((select is_staff()));

-- inventory_movements: inventory_movements: lab + admin write
drop policy "inventory_movements: lab + admin write" on public."inventory_movements";
create policy "inventory_movements: lab + admin write" on public."inventory_movements"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text, 'medtech'::text, 'xray_technician'::text])))
  with check ((select has_role(ARRAY['admin'::text, 'medtech'::text, 'xray_technician'::text])));

-- inventory_movements: inventory_movements: staff read
drop policy "inventory_movements: staff read" on public."inventory_movements";
create policy "inventory_movements: staff read" on public."inventory_movements"
  as permissive
  for select
  to authenticated
  using ((select is_staff()));

-- journal_entries: journal_entries: admin read
drop policy "journal_entries: admin read" on public."journal_entries";
create policy "journal_entries: admin read" on public."journal_entries"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- journal_lines: journal_lines: admin read
drop policy "journal_lines: admin read" on public."journal_lines";
create policy "journal_lines: admin read" on public."journal_lines"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- newsletter_campaigns: newsletter_campaigns: admin all
drop policy "newsletter_campaigns: admin all" on public."newsletter_campaigns";
create policy "newsletter_campaigns: admin all" on public."newsletter_campaigns"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- package_components: package_components: admin write
drop policy "package_components: admin write" on public."package_components";
create policy "package_components: admin write" on public."package_components"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- package_components: package_components: staff read
drop policy "package_components: staff read" on public."package_components";
create policy "package_components: staff read" on public."package_components"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- patients: patients: patient self select
drop policy "patients: patient self select" on public."patients";
create policy "patients: patient self select" on public."patients"
  as permissive
  for select
  to anon, authenticated
  using ((id = (select current_patient_id())));

-- patients: patients: staff full
drop policy "patients: staff full" on public."patients";
create policy "patients: staff full" on public."patients"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])))
  with check ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- payment_method_account_map: payment_method_account_map: admin read
drop policy "payment_method_account_map: admin read" on public."payment_method_account_map";
create policy "payment_method_account_map: admin read" on public."payment_method_account_map"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- payments: payments: patient self select
drop policy "payments: patient self select" on public."payments";
create policy "payments: patient self select" on public."payments"
  as permissive
  for select
  to anon, authenticated
  using ((visit_id IN ( SELECT visits.id
   FROM visits
  WHERE (visits.patient_id = (select current_patient_id())))));

-- payments: payments: reception/admin manage
drop policy "payments: reception/admin manage" on public."payments";
create policy "payments: reception/admin manage" on public."payments"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'admin'::text])))
  with check ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- payroll_contribution_brackets: payroll_contribution_brackets: admin all
drop policy "payroll_contribution_brackets: admin all" on public."payroll_contribution_brackets";
create policy "payroll_contribution_brackets: admin all" on public."payroll_contribution_brackets"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- payroll_deduction_lines: payroll_deduction_lines: admin all
drop policy "payroll_deduction_lines: admin all" on public."payroll_deduction_lines";
create policy "payroll_deduction_lines: admin all" on public."payroll_deduction_lines"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- payroll_deduction_lines: payroll_deduction_lines: self read
drop policy "payroll_deduction_lines: self read" on public."payroll_deduction_lines";
create policy "payroll_deduction_lines: self read" on public."payroll_deduction_lines"
  as permissive
  for select
  to authenticated
  using ((employee_run_id IN ( SELECT per.id
   FROM (payroll_employee_runs per
     JOIN employees e ON ((e.id = per.employee_id)))
  WHERE (e.staff_profile_id = (select auth.uid())))));

-- payroll_dtr_imports: payroll_dtr_imports: admin all
drop policy "payroll_dtr_imports: admin all" on public."payroll_dtr_imports";
create policy "payroll_dtr_imports: admin all" on public."payroll_dtr_imports"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- payroll_dtr_rows: payroll_dtr_rows: admin all
drop policy "payroll_dtr_rows: admin all" on public."payroll_dtr_rows";
create policy "payroll_dtr_rows: admin all" on public."payroll_dtr_rows"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- payroll_earning_lines: payroll_earning_lines: admin all
drop policy "payroll_earning_lines: admin all" on public."payroll_earning_lines";
create policy "payroll_earning_lines: admin all" on public."payroll_earning_lines"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- payroll_earning_lines: payroll_earning_lines: self read
drop policy "payroll_earning_lines: self read" on public."payroll_earning_lines";
create policy "payroll_earning_lines: self read" on public."payroll_earning_lines"
  as permissive
  for select
  to authenticated
  using ((employee_run_id IN ( SELECT per.id
   FROM (payroll_employee_runs per
     JOIN employees e ON ((e.id = per.employee_id)))
  WHERE (e.staff_profile_id = (select auth.uid())))));

-- payroll_employee_runs: payroll_employee_runs: admin all
drop policy "payroll_employee_runs: admin all" on public."payroll_employee_runs";
create policy "payroll_employee_runs: admin all" on public."payroll_employee_runs"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- payroll_employee_runs: payroll_employee_runs: self read
drop policy "payroll_employee_runs: self read" on public."payroll_employee_runs";
create policy "payroll_employee_runs: self read" on public."payroll_employee_runs"
  as permissive
  for select
  to authenticated
  using ((employee_id IN ( SELECT employees.id
   FROM employees
  WHERE (employees.staff_profile_id = (select auth.uid())))));

-- payroll_holidays: payroll_holidays: admin read
drop policy "payroll_holidays: admin read" on public."payroll_holidays";
create policy "payroll_holidays: admin read" on public."payroll_holidays"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- payroll_holidays: payroll_holidays: admin write
drop policy "payroll_holidays: admin write" on public."payroll_holidays";
create policy "payroll_holidays: admin write" on public."payroll_holidays"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- payroll_ot_slips: payroll_ot_slips: admin all
drop policy "payroll_ot_slips: admin all" on public."payroll_ot_slips";
create policy "payroll_ot_slips: admin all" on public."payroll_ot_slips"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- payroll_ot_slips: payroll_ot_slips: self read
drop policy "payroll_ot_slips: self read" on public."payroll_ot_slips";
create policy "payroll_ot_slips: self read" on public."payroll_ot_slips"
  as permissive
  for select
  to authenticated
  using ((employee_id IN ( SELECT employees.id
   FROM employees
  WHERE (employees.staff_profile_id = (select auth.uid())))));

-- payroll_periods: payroll_periods: admin all
drop policy "payroll_periods: admin all" on public."payroll_periods";
create policy "payroll_periods: admin all" on public."payroll_periods"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- payroll_runs: payroll_runs: admin all
drop policy "payroll_runs: admin all" on public."payroll_runs";
create policy "payroll_runs: admin all" on public."payroll_runs"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- payroll_wt_brackets: payroll_wt_brackets: admin all
drop policy "payroll_wt_brackets: admin all" on public."payroll_wt_brackets";
create policy "payroll_wt_brackets: admin all" on public."payroll_wt_brackets"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- physician_compensation: physician_compensation: admin manage
drop policy "physician_compensation: admin manage" on public."physician_compensation";
create policy "physician_compensation: admin manage" on public."physician_compensation"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- physician_schedule_overrides: physician_overrides: admin manage
drop policy "physician_overrides: admin manage" on public."physician_schedule_overrides";
create policy "physician_overrides: admin manage" on public."physician_schedule_overrides"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- physician_schedules: physician_schedules: admin manage
drop policy "physician_schedules: admin manage" on public."physician_schedules";
create policy "physician_schedules: admin manage" on public."physician_schedules"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- physician_specialties: physician_specialties: admin manage
drop policy "physician_specialties: admin manage" on public."physician_specialties";
create policy "physician_specialties: admin manage" on public."physician_specialties"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- physicians: physicians: admin manage
drop policy "physicians: admin manage" on public."physicians";
create policy "physicians: admin manage" on public."physicians"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- physicians: physicians: staff read all
drop policy "physicians: staff read all" on public."physicians";
create policy "physicians: staff read all" on public."physicians"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- rate_limit_attempts: rate_limit_attempts: admin read
drop policy "rate_limit_attempts: admin read" on public."rate_limit_attempts";
create policy "rate_limit_attempts: admin read" on public."rate_limit_attempts"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- recurring_bill_templates: recurring_bill_templates_admin_all
drop policy "recurring_bill_templates_admin_all" on public."recurring_bill_templates";
create policy "recurring_bill_templates_admin_all" on public."recurring_bill_templates"
  as permissive
  for all
  to public
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- report_group_service_params: report_group_service_params: admin write
drop policy "report_group_service_params: admin write" on public."report_group_service_params";
create policy "report_group_service_params: admin write" on public."report_group_service_params"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- report_group_service_params: report_group_service_params: staff read
drop policy "report_group_service_params: staff read" on public."report_group_service_params";
create policy "report_group_service_params: staff read" on public."report_group_service_params"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- report_groups: report_groups: admin manage
drop policy "report_groups: admin manage" on public."report_groups";
create policy "report_groups: admin manage" on public."report_groups"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- report_groups: report_groups: staff read
drop policy "report_groups: staff read" on public."report_groups";
create policy "report_groups: staff read" on public."report_groups"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text])));

-- result_amendments: result_amendments: medtech/pathologist/admin write
drop policy "result_amendments: medtech/pathologist/admin write" on public."result_amendments";
create policy "result_amendments: medtech/pathologist/admin write" on public."result_amendments"
  as permissive
  for insert
  to authenticated
  with check ((select has_role(ARRAY['medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- result_amendments: result_amendments: staff read
drop policy "result_amendments: staff read" on public."result_amendments";
create policy "result_amendments: staff read" on public."result_amendments"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- result_template_param_ranges: result_template_param_ranges: admin manage
drop policy "result_template_param_ranges: admin manage" on public."result_template_param_ranges";
create policy "result_template_param_ranges: admin manage" on public."result_template_param_ranges"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- result_template_param_ranges: result_template_param_ranges: staff read
drop policy "result_template_param_ranges: staff read" on public."result_template_param_ranges";
create policy "result_template_param_ranges: staff read" on public."result_template_param_ranges"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- result_template_params: result_template_params: admin manage
drop policy "result_template_params: admin manage" on public."result_template_params";
create policy "result_template_params: admin manage" on public."result_template_params"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- result_template_params: result_template_params: staff read
drop policy "result_template_params: staff read" on public."result_template_params";
create policy "result_template_params: staff read" on public."result_template_params"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- result_templates: result_templates: admin manage
drop policy "result_templates: admin manage" on public."result_templates";
create policy "result_templates: admin manage" on public."result_templates"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- result_templates: result_templates: staff read
drop policy "result_templates: staff read" on public."result_templates";
create policy "result_templates: staff read" on public."result_templates"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- result_test_requests: result_test_requests: admin manage
drop policy "result_test_requests: admin manage" on public."result_test_requests";
create policy "result_test_requests: admin manage" on public."result_test_requests"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- result_test_requests: result_test_requests: patient released only
drop policy "result_test_requests: patient released only" on public."result_test_requests";
create policy "result_test_requests: patient released only" on public."result_test_requests"
  as permissive
  for select
  to anon, authenticated
  using ((EXISTS ( SELECT 1
   FROM (test_requests tr
     JOIN visits v ON ((v.id = tr.visit_id)))
  WHERE ((tr.id = result_test_requests.test_request_id) AND (tr.status = 'released'::text) AND (v.patient_id = (select current_patient_id()))))));

-- result_test_requests: result_test_requests: staff read
drop policy "result_test_requests: staff read" on public."result_test_requests";
create policy "result_test_requests: staff read" on public."result_test_requests"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- result_values: result_values: admin delete
drop policy "result_values: admin delete" on public."result_values";
create policy "result_values: admin delete" on public."result_values"
  as permissive
  for delete
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- result_values: result_values: medtech update own claimed test
drop policy "result_values: medtech update own claimed test" on public."result_values";
create policy "result_values: medtech update own claimed test" on public."result_values"
  as permissive
  for update
  to authenticated
  using (((select has_role(ARRAY['medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])) AND (EXISTS ( SELECT 1
   FROM (result_test_requests rtr
     JOIN test_requests tr ON ((tr.id = rtr.test_request_id)))
  WHERE ((rtr.result_id = result_values.result_id) AND ((select has_role(ARRAY['pathologist'::text, 'admin'::text])) OR ((tr.assigned_to = (select auth.uid())) AND (tr.status = ANY (ARRAY['in_progress'::text, 'result_uploaded'::text])))))))))
  with check (((select has_role(ARRAY['medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])) AND (EXISTS ( SELECT 1
   FROM (result_test_requests rtr
     JOIN test_requests tr ON ((tr.id = rtr.test_request_id)))
  WHERE ((rtr.result_id = result_values.result_id) AND ((select has_role(ARRAY['pathologist'::text, 'admin'::text])) OR ((tr.assigned_to = (select auth.uid())) AND (tr.status = ANY (ARRAY['in_progress'::text, 'result_uploaded'::text])))))))));

-- result_values: result_values: medtech write own claimed test
drop policy "result_values: medtech write own claimed test" on public."result_values";
create policy "result_values: medtech write own claimed test" on public."result_values"
  as permissive
  for insert
  to authenticated
  with check (((select has_role(ARRAY['medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])) AND (EXISTS ( SELECT 1
   FROM (result_test_requests rtr
     JOIN test_requests tr ON ((tr.id = rtr.test_request_id)))
  WHERE ((rtr.result_id = result_values.result_id) AND ((select has_role(ARRAY['pathologist'::text, 'admin'::text])) OR ((tr.assigned_to = (select auth.uid())) AND (tr.status = ANY (ARRAY['in_progress'::text, 'result_uploaded'::text])))))))));

-- result_values: result_values: read by owning medtech + pathologist + admin
drop policy "result_values: read by owning medtech + pathologist + admin" on public."result_values";
create policy "result_values: read by owning medtech + pathologist + admin" on public."result_values"
  as permissive
  for select
  to authenticated
  using (((select has_role(ARRAY['pathologist'::text, 'admin'::text])) OR (EXISTS ( SELECT 1
   FROM (result_test_requests rtr
     JOIN test_requests tr ON ((tr.id = rtr.test_request_id)))
  WHERE ((rtr.result_id = result_values.result_id) AND (tr.assigned_to = (select auth.uid())) AND (select has_role(ARRAY['medtech'::text, 'xray_technician'::text])))))));

-- results: results: medtech/pathologist/admin write
drop policy "results: medtech/pathologist/admin write" on public."results";
create policy "results: medtech/pathologist/admin write" on public."results"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])))
  with check ((select has_role(ARRAY['medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- results: results: patient released only
drop policy "results: patient released only" on public."results";
create policy "results: patient released only" on public."results"
  as permissive
  for select
  to anon, authenticated
  using ((EXISTS ( SELECT 1
   FROM ((result_test_requests rtr
     JOIN test_requests tr ON ((tr.id = rtr.test_request_id)))
     JOIN visits v ON ((v.id = tr.visit_id)))
  WHERE ((rtr.result_id = results.id) AND (tr.status = 'released'::text) AND (v.patient_id = (select current_patient_id()))))));

-- results: results: staff select
drop policy "results: staff select" on public."results";
create policy "results: staff select" on public."results"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- service_price_history: service_price_history: staff read
drop policy "service_price_history: staff read" on public."service_price_history";
create policy "service_price_history: staff read" on public."service_price_history"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- services: services: admin all
drop policy "services: admin all" on public."services";
create policy "services: admin all" on public."services"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- services: services: staff read
drop policy "services: staff read" on public."services";
create policy "services: staff read" on public."services"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'xray_technician'::text])));

-- specialty_codes: specialty_codes: admin manage
drop policy "specialty_codes: admin manage" on public."specialty_codes";
create policy "specialty_codes: admin manage" on public."specialty_codes"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- staff_advances: staff_advances: admin all
drop policy "staff_advances: admin all" on public."staff_advances";
create policy "staff_advances: admin all" on public."staff_advances"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- staff_advances: staff_advances: reception read
drop policy "staff_advances: reception read" on public."staff_advances";
create policy "staff_advances: reception read" on public."staff_advances"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- staff_profiles: staff_profiles: admin manage
drop policy "staff_profiles: admin manage" on public."staff_profiles";
create policy "staff_profiles: admin manage" on public."staff_profiles"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- staff_profiles: staff_profiles: self select
drop policy "staff_profiles: self select" on public."staff_profiles";
create policy "staff_profiles: self select" on public."staff_profiles"
  as permissive
  for select
  to authenticated
  using ((id = (select auth.uid())));

-- staff_profiles: staff_profiles: staff read
drop policy "staff_profiles: staff read" on public."staff_profiles";
create policy "staff_profiles: staff read" on public."staff_profiles"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- subscribers: subscribers: admin all
drop policy "subscribers: admin all" on public."subscribers";
create policy "subscribers: admin all" on public."subscribers"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- sync_state: sync_state: admin read
drop policy "sync_state: admin read" on public."sync_state";
create policy "sync_state: admin read" on public."sync_state"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['admin'::text])));

-- test_requests: test_requests: medtech/pathologist update
drop policy "test_requests: medtech/pathologist update" on public."test_requests";
create policy "test_requests: medtech/pathologist update" on public."test_requests"
  as permissive
  for update
  to authenticated
  using ((select has_role(ARRAY['medtech'::text, 'pathologist'::text, 'xray_technician'::text])))
  with check ((select has_role(ARRAY['medtech'::text, 'pathologist'::text, 'xray_technician'::text])));

-- test_requests: test_requests: patient own visits
drop policy "test_requests: patient own visits" on public."test_requests";
create policy "test_requests: patient own visits" on public."test_requests"
  as permissive
  for select
  to anon, authenticated
  using ((visit_id IN ( SELECT v.id
   FROM visits v
  WHERE (v.patient_id = (select current_patient_id())))));

-- test_requests: test_requests: reception/admin write
drop policy "test_requests: reception/admin write" on public."test_requests";
create policy "test_requests: reception/admin write" on public."test_requests"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'admin'::text])))
  with check ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- test_requests: test_requests: staff select
drop policy "test_requests: staff select" on public."test_requests";
create policy "test_requests: staff select" on public."test_requests"
  as permissive
  for select
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));

-- vendors: vendors_admin_all
drop policy "vendors_admin_all" on public."vendors";
create policy "vendors_admin_all" on public."vendors"
  as permissive
  for all
  to public
  using ((select has_role(ARRAY['admin'::text])))
  with check ((select has_role(ARRAY['admin'::text])));

-- visit_pins: visit_pins: reception/admin manage
drop policy "visit_pins: reception/admin manage" on public."visit_pins";
create policy "visit_pins: reception/admin manage" on public."visit_pins"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'admin'::text])))
  with check ((select has_role(ARRAY['reception'::text, 'admin'::text])));

-- visits: visits: patient self select
drop policy "visits: patient self select" on public."visits";
create policy "visits: patient self select" on public."visits"
  as permissive
  for select
  to anon, authenticated
  using ((patient_id = (select current_patient_id())));

-- visits: visits: staff full
drop policy "visits: staff full" on public."visits";
create policy "visits: staff full" on public."visits"
  as permissive
  for all
  to authenticated
  using ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])))
  with check ((select has_role(ARRAY['reception'::text, 'medtech'::text, 'pathologist'::text, 'admin'::text, 'xray_technician'::text])));


-- ---------------------------------------------------------------------------
-- Phase 2 — consolidate stacked permissive SELECT policies (hand-written)
-- ---------------------------------------------------------------------------
--
-- Nine tables carry TWO permissive SELECT policies covering the same role, so both
-- are evaluated for every row. Merging them puts the cheap staff check first and
-- lets the expensive patient subquery short-circuit for staff sessions.
--
-- THE RULE: consolidate WITHIN a role list, never across one.
--
-- Several of these pairs have different role lists — e.g. `services: public read
-- active` is {anon, authenticated} while `services: staff read` is {authenticated}.
-- Merging those into one policy over the union would widen the expression anon can
-- reach, and that is precisely how the two live anon-readable exposures found on
-- 2026-09-10 (292 patients via v_hmo_*, 20 doctors' pay terms via physicians) came
-- about. So each pair is split by role first: anon keeps a policy whose expression
-- is byte-identical to what it has today, and only `authenticated` gets the OR'd
-- form. Two permissive policies OR together, so the OR is exactly equivalent.
--
-- The `ALL`-command policies on these tables (admin manage / reception write / …)
-- also apply to SELECT, but they are a different cmd group and are left untouched —
-- consolidating across cmd would change what INSERT and UPDATE check.
--
-- Row visibility is proved unchanged per table per principal, anon included, by
-- scripts/perf/rls-equivalence-prove.ts. Unlike Phase 1 this is NOT inert by
-- construction, which is why it is gated on sampling and lands as its own commit.

-- appointment_attachments ---------------------------------------------------
drop policy "appointment_attachments: patient self" on public.appointment_attachments;
drop policy "appointment_attachments: staff read" on public.appointment_attachments;

create policy "appointment_attachments: anon patient self" on public.appointment_attachments
  as permissive for select to anon
  using (patient_id = (select current_patient_id()));

create policy "appointment_attachments: authenticated read" on public.appointment_attachments
  as permissive for select to authenticated
  using ((select is_staff()) or patient_id = (select current_patient_id()));

-- hmo_providers -------------------------------------------------------------
drop policy "hmo_providers: public read active" on public.hmo_providers;
drop policy "hmo_providers: staff read all" on public.hmo_providers;

create policy "hmo_providers: anon read active" on public.hmo_providers
  as permissive for select to anon
  using (is_active = true);

create policy "hmo_providers: authenticated read" on public.hmo_providers
  as permissive for select to authenticated
  using (
    (select has_role(array['reception','medtech','pathologist','admin','xray_technician']))
    or is_active = true
  );

-- physicians ----------------------------------------------------------------
drop policy "physicians: public read active" on public.physicians;
drop policy "physicians: staff read all" on public.physicians;

create policy "physicians: anon read active" on public.physicians
  as permissive for select to anon
  using (is_active = true);

create policy "physicians: authenticated read" on public.physicians
  as permissive for select to authenticated
  using (
    (select has_role(array['reception','medtech','pathologist','admin','xray_technician']))
    or is_active = true
  );

-- report_groups -------------------------------------------------------------
-- NOTE: the staff arm here is FOUR roles, not five — xray_technician is absent.
-- Copied as-is; widening it would be a behaviour change smuggled into a perf PR.
drop policy "report_groups: public read active" on public.report_groups;
drop policy "report_groups: staff read" on public.report_groups;

create policy "report_groups: anon read active" on public.report_groups
  as permissive for select to anon
  using (is_active = true);

create policy "report_groups: authenticated read" on public.report_groups
  as permissive for select to authenticated
  using (
    (select has_role(array['reception','medtech','pathologist','admin']))
    or is_active = true
  );

-- result_test_requests ------------------------------------------------------
drop policy "result_test_requests: patient released only" on public.result_test_requests;
drop policy "result_test_requests: staff read" on public.result_test_requests;

create policy "result_test_requests: anon patient released only" on public.result_test_requests
  as permissive for select to anon
  using (
    exists (
      select 1
        from public.test_requests tr
        join public.visits v on v.id = tr.visit_id
       where tr.id = result_test_requests.test_request_id
         and tr.status = 'released'
         and v.patient_id = (select current_patient_id())
    )
  );

create policy "result_test_requests: authenticated read" on public.result_test_requests
  as permissive for select to authenticated
  using (
    (select has_role(array['reception','medtech','pathologist','admin','xray_technician']))
    or exists (
      select 1
        from public.test_requests tr
        join public.visits v on v.id = tr.visit_id
       where tr.id = result_test_requests.test_request_id
         and tr.status = 'released'
         and v.patient_id = (select current_patient_id())
    )
  );

-- results -------------------------------------------------------------------
drop policy "results: patient released only" on public.results;
drop policy "results: staff select" on public.results;

create policy "results: anon patient released only" on public.results
  as permissive for select to anon
  using (
    exists (
      select 1
        from public.result_test_requests rtr
        join public.test_requests tr on tr.id = rtr.test_request_id
        join public.visits v on v.id = tr.visit_id
       where rtr.result_id = results.id
         and tr.status = 'released'
         and v.patient_id = (select current_patient_id())
    )
  );

create policy "results: authenticated read" on public.results
  as permissive for select to authenticated
  using (
    (select has_role(array['reception','medtech','pathologist','admin','xray_technician']))
    or exists (
      select 1
        from public.result_test_requests rtr
        join public.test_requests tr on tr.id = rtr.test_request_id
        join public.visits v on v.id = tr.visit_id
       where rtr.result_id = results.id
         and tr.status = 'released'
         and v.patient_id = (select current_patient_id())
    )
  );

-- services ------------------------------------------------------------------
-- NOTE: the staff arm excludes admin — admin reaches services through the separate
-- `services: admin all` ALL policy, which is a different cmd group and untouched.
drop policy "services: public read active" on public.services;
drop policy "services: staff read" on public.services;

create policy "services: anon read active" on public.services
  as permissive for select to anon
  using (is_active = true);

create policy "services: authenticated read" on public.services
  as permissive for select to authenticated
  using (
    (select has_role(array['reception','medtech','pathologist','xray_technician']))
    or is_active = true
  );

-- staff_profiles ------------------------------------------------------------
-- Both arms are already {authenticated}-only, so there is no role split to make.
drop policy "staff_profiles: self select" on public.staff_profiles;
drop policy "staff_profiles: staff read" on public.staff_profiles;

create policy "staff_profiles: authenticated read" on public.staff_profiles
  as permissive for select to authenticated
  using (
    (select has_role(array['reception','medtech','pathologist','admin','xray_technician']))
    or id = (select auth.uid())
  );

-- test_requests -------------------------------------------------------------
-- The `reception/admin write` ALL policy and the `medtech/pathologist update`
-- UPDATE policy are different cmd groups and stay as they are.
drop policy "test_requests: patient own visits" on public.test_requests;
drop policy "test_requests: staff select" on public.test_requests;

create policy "test_requests: anon patient own visits" on public.test_requests
  as permissive for select to anon
  using (
    visit_id in (
      select v.id from public.visits v
       where v.patient_id = (select current_patient_id())
    )
  );

create policy "test_requests: authenticated read" on public.test_requests
  as permissive for select to authenticated
  using (
    (select has_role(array['reception','medtech','pathologist','admin','xray_technician']))
    or visit_id in (
      select v.id from public.visits v
       where v.patient_id = (select current_patient_id())
    )
  );
